version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: knowledge_pageable_endpoint_postgres
    environment:
      POSTGRES_DB: Users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"